=begin
#NSX Policy API

#VMware NSX Policy REST API

OpenAPI spec version: 9.0.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.46

=end

require 'date'

module Nsxt9PolicyClient
  # VPC Subnet DHCP config 
  class VpcSubnetDhcpConfig
    attr_accessor :static_pool_config

    # This is used to enable or disable DHCP at VPC Subnet. True: to override DHCP config at VPC/VPC Service Profile. False: to disable DHCP, other DHCP configurations are not allowed to be configured. 
    attr_accessor :enable_dhcp

    # If configured then subnet will be configured with the DHCP Relay. Configure dhcp_relay_config is a recommended option to configure DHCP relay on subnet. 
    attr_accessor :dhcp_relay_config_path

    attr_accessor :dns_client_config

    # DHCP lease time in seconds. When specified, this property overwrites lease time configured DHCP server config. The default lease time is 86,400 seconds. In DHCP_RELAY mode, any specified lease time will be ignored. 
    attr_accessor :lease_time

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'static_pool_config' => :'static_pool_config',
        :'enable_dhcp' => :'enable_dhcp',
        :'dhcp_relay_config_path' => :'dhcp_relay_config_path',
        :'dns_client_config' => :'dns_client_config',
        :'lease_time' => :'lease_time'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'static_pool_config' => :'StaticPoolConfig',
        :'enable_dhcp' => :'BOOLEAN',
        :'dhcp_relay_config_path' => :'String',
        :'dns_client_config' => :'DnsClientConfig',
        :'lease_time' => :'Integer'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'static_pool_config')
        self.static_pool_config = attributes[:'static_pool_config']
      end

      if attributes.has_key?(:'enable_dhcp')
        self.enable_dhcp = attributes[:'enable_dhcp']
      end

      if attributes.has_key?(:'dhcp_relay_config_path')
        self.dhcp_relay_config_path = attributes[:'dhcp_relay_config_path']
      end

      if attributes.has_key?(:'dns_client_config')
        self.dns_client_config = attributes[:'dns_client_config']
      end

      if attributes.has_key?(:'lease_time')
        self.lease_time = attributes[:'lease_time']
      else
        self.lease_time = 86400
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@lease_time.nil? && @lease_time > 4294967295
        invalid_properties.push('invalid value for "lease_time", must be smaller than or equal to 4294967295.')
      end

      if !@lease_time.nil? && @lease_time < 60
        invalid_properties.push('invalid value for "lease_time", must be greater than or equal to 60.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@lease_time.nil? && @lease_time > 4294967295
      return false if !@lease_time.nil? && @lease_time < 60
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] lease_time Value to be assigned
    def lease_time=(lease_time)
      if !lease_time.nil? && lease_time > 4294967295
        fail ArgumentError, 'invalid value for "lease_time", must be smaller than or equal to 4294967295.'
      end

      if !lease_time.nil? && lease_time < 60
        fail ArgumentError, 'invalid value for "lease_time", must be greater than or equal to 60.'
      end

      @lease_time = lease_time
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          static_pool_config == o.static_pool_config &&
          enable_dhcp == o.enable_dhcp &&
          dhcp_relay_config_path == o.dhcp_relay_config_path &&
          dns_client_config == o.dns_client_config &&
          lease_time == o.lease_time
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [static_pool_config, enable_dhcp, dhcp_relay_config_path, dns_client_config, lease_time].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = Nsxt9PolicyClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
