---
name: zookeeper

releases:
- name: zookeeper
  version: 0.0.5
  url: https://bosh.io/d/github.com/cppforlife/zookeeper-release?v=0.0.5
  sha1: 65a07b7526f108b0863d76aada7fc29e2c9e2095

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  stemcell: default
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: instance-zoo
  azs: [z1]
  instances: 35
  jobs:
  - name: zookeeper
    release: zookeeper
    properties: {}
  stemcell: default
  vm_type:  default
  persistent_disk_pool: default
  networks:
  - name: default
