platform: linux
image_resource:
  { type: docker-image, source: { repository: gcr.io/round-essence-187720/vcpici-vcpi-main } }

inputs:
  - name: source-ci
  - name: certification
  - name: environment
  - name: bats
  - name: director-state
  - name: bosh-cli
  - name: stemcell

run:
  path: source-ci/ci/tasks/run-bats-policy.sh

params:
  STEMCELL_NAME:      ""
  BAT_RSPEC_FLAGS:    ""
