ignore:
  - 'lib/nsxt_manager_client/**/*'
  - 'lib/nsxt_policy_client/**/*'
  - 'lib/ruby_vim_sdk/**/*'
  - 'lib/ruby_vim_sdk.rb'
  - 'lib/vmodl_version.rb'
  - 'lib/cloud/vsphere.rb':
    - Style/GlobalVars
  - 'lib/cloud/vsphere/cloud.rb':
    - Lint/AssignmentInCondition
    - Layout/BlockAlignment
    - Style/For
    - Style/InfiniteLoop
    - Style/FileNull
  - 'lib/cloud/vsphere/config.rb':
    - Style/UnlessLogicalOperators
    - Performance/RedundantMerge
  - 'lib/cloud/vsphere/helpers/xml.rb':
    - Naming/VariableName
  - 'lib/cloud/vsphere/soap_stub.rb':
    - Style/GlobalVars
  - 'lib/cloud/vsphere/vm_config.rb':
    - Naming/VariableName
    - Style/RedundantInterpolation
  - 'lib/cloud/vsphere/vm_type.rb':
    - Lint/DuplicateMethods
  - 'lib/cloud/vsphere/cloud_searcher.rb':
    - Style/SafeNavigation
    - Style/LineEndConcatenation
  - 'lib/cloud/vsphere/file_provider.rb':
    - Style/LineEndConcatenation
  - 'lib/cloud/vsphere/lease_obtainer.rb':
    - Style/LineEndConcatenation
  - 'lib/cloud/vsphere/models/network_definition.rb':
    - Style/SlicingWithRange
  - 'lib/cloud/vsphere/nsxt_policy_provider.rb':
    - Style/AndOr
  - 'lib/cloud/vsphere/resources/datacenter.rb':
    - Lint/InheritException
  - 'lib/cloud/vsphere/resources/storage_pod.rb':
    - Style/ClassEqualityComparison
  - 'lib/cloud/vsphere/resources/vm.rb':
    - Style/LineEndConcatenation
    - Style/SafeNavigation
  - 'lib/cloud/vsphere/stemcell.rb':
    - Style/ClassEqualityComparison
  - 'spec/**/*'
  - 'lib/cloud/vsphere/vm_creator.rb':
    - Style/ClassCheck
