source 'https://rubygems.org'

gem 'bosh_common', '1.3262.24.0'
gem 'bosh_cpi',    '2.4.1'
gem 'membrane',    '~>1.1.0'
gem 'builder',     '~>3.2.3'
gem 'nokogiri',    '~>1.7.1'
gem 'mono_logger', '~>1.1.0'
gem 'oga', '2.3'

group :development, :test do
  gem 'fakefs'
  gem 'parallel_tests'
  gem 'pry'
  gem 'pry-byebug'
  gem 'rack', '~> 2.0.1'
  gem 'rake', '~>10.0'
  gem 'rspec', '~> 3.5.0'
  gem 'rspec-instafail'
  gem 'rspec-its'
  gem 'simplecov', :require => false
  gem 'timecop', '~>0.8.1'
end
