require 'fileutils'

# Remove did_you_mean as it's very annoying in a Rakefile
DidYouMean::Correctable.send(:remove_method, :to_s) if defined? DidYouMean

# Colorize error messages when the trace output is a TTY
module ColorizeExceptionMessageDetails
  def display_exception_message_details(ex)
    return super unless (options.trace_output || $stderr)&.isatty
    if ex.instance_of?(RuntimeError)
      trace "\e[31;01m#{ex.message}\e[0m"
    else
      trace "\e[31;01m#{ex.class.name}: \e[0m#{ex.message}"
    end
  end
end
Rake::Application.send(:prepend, ColorizeExceptionMessageDetails)

desc 'Create swagger client from swagger spec'
namespace :swagger do
  task :nsxt_manager_client do
  
    rm_rf(["./lib/nsxt_manager_client/*"])
  
    #generate all models
    sh [
      "swagger-codegen generate",
      "-i ./data/nsxt_manager_api/nsxt_manager_api.json",
      "-l ruby",
      "-o ./lib/nsxt_manager_client",
      "-c ./data/nsxt_manager_api/config.json -t ./data/swagger-nsxt-template"
    ].join(' ')
  
    #Patch models that have wrong _deserialize method
    #TODO: Patch both LogicalRouterPortListResult and LogicalPortAttachment in 1 call
    sh [
       "swagger-codegen generate",
       "-i ./data/nsxt_manager_api/nsxt_manager_api.json",
       "-l ruby",
       "-o ./lib/nsxt_manager_client",
       "-c ./data/nsxt_manager_api/config.json -t ./data/swagger-nsxt-template-deserialization",
       "-Dmodels=LogicalRouterPortListResult"
     ].join(' ')
  
    #Patch LogicalPortAttachment which also has wrong _deserialize method
    sh [
       "swagger-codegen generate",
       "-i ./data/nsxt_manager_api/nsxt_manager_api.json",
       "-l ruby",
       "-o ./lib/nsxt_manager_client",
       "-c ./data/nsxt_manager_api/config.json -t ./data/swagger-nsxt-template-deserialization",
       "-Dmodels=LogicalPortAttachment"
     ].join(' ')
  
    rm_rf (["./lib/nsxt_manager_client/.swagger-codegen-ignore",
      "./lib/nsxt_manager_client/.swagger-codegen",
      "./lib/nsxt_manager_client/README.md",
      "./lib/nsxt_manager_client/.rspec",
      "./lib/nsxt_manager_client/.gitignore",
      "./lib/nsxt_manager_client/Gemfile",
      "./lib/nsxt_manager_client/git_push.sh",
      "./lib/nsxt_manager_client/docs",
      "./lib/nsxt_manager_client/spec",
      "./lib/nsxt_manager_client/nsxt_manager_client.gemspec",
      "./lib/nsxt_manager_client/Rakefile",
      "./lib/nsxt_manager_client/nsxt_manager_client"
    ])
  
    mv("./lib/nsxt_manager_client/lib/nsxt_manager_client", "./lib/nsxt_manager_client/nsxt_manager_client")
  
    mv("./lib/nsxt_manager_client/lib/nsxt_manager_client.rb", "./lib/nsxt_manager_client/nsxt_manager_client.rb")
  
    rm_rf(["./lib/nsxt_manager_client/lib"])
  
    # Prepend load.unshift line
    # read the file
    f = File.open("lib/nsxt_manager_client/nsxt_manager_client.rb", "r+")
    lines = f.readlines
    f.close
    # Add line
    str = "$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '..', 'nsxt_manager_client'))\n"
    lines = [str] + lines
    output = File.new("lib/nsxt_manager_client/nsxt_manager_client.rb", "w")
    lines.each { |line| output.write line }
    output.close
  end

  task :nsxt_policy_client do
  
    rm_rf(["./lib/nsxt_policy_client/*"])
  
    #generate all models
    sh [
      "swagger-codegen generate",
      "-i ./data/nsxt_policy_api/nsxt_policy_api.json",
      "-l ruby",
      "-o ./lib/nsxt_policy_client",
      "-c ./data/nsxt_policy_api/config.json -t ./data/swagger-nsxt-template"
    ].join(' ')
  
    sh [
       "swagger-codegen generate",
       "-i ./data/nsxt_policy_api/nsxt_policy_api.json",
       "-l ruby",
       "-o ./lib/nsxt_policy_client",
       "-c ./data/nsxt_policy_api/config.json -t ./data/nsxt_policy_api/virtual_machine_patch",
       "-Dmodels=RealizedVirtualMachine"
     ].join(' ')

    #Patch Group which has wrong _deserialize method
    sh [
           "swagger-codegen generate",
           "-i ./data/nsxt_policy_api/nsxt_policy_api.json",
           "-l ruby",
           "-o ./lib/nsxt_policy_client",
           "-c ./data/nsxt_policy_api/config.json -t ./data/swagger-nsxt-template-deserialization",
           "-Dmodels=Group"
       ].join(' ')

    rm_rf (["./lib/nsxt_policy_client/.swagger-codegen-ignore",
      "./lib/nsxt_policy_client/.swagger-codegen",
      "./lib/nsxt_policy_client/README.md",
      "./lib/nsxt_policy_client/.rspec",
      "./lib/nsxt_policy_client/.gitignore",
      "./lib/nsxt_policy_client/Gemfile",
      "./lib/nsxt_policy_client/git_push.sh",
      "./lib/nsxt_policy_client/docs",
      "./lib/nsxt_policy_client/spec",
      "./lib/nsxt_policy_client/nsxt_policy_client.gemspec",
      "./lib/nsxt_policy_client/Rakefile",
      "./lib/nsxt_policy_client/nsxt_policy_client"
    ])
  
    mv("./lib/nsxt_policy_client/lib/nsxt_policy_client", "./lib/nsxt_policy_client/nsxt_policy_client")
  
    mv("./lib/nsxt_policy_client/lib/nsxt_policy_client.rb", "./lib/nsxt_policy_client/nsxt_policy_client.rb")
  
    rm_rf(["./lib/nsxt_policy_client/lib"])
  
    # Prepend load.unshift line
    # read the file
    f = File.open("lib/nsxt_policy_client/nsxt_policy_client.rb", "r+")
    lines = f.readlines
    f.close
    # Add line
    str = "$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '..', 'nsxt_policy_client'))\n"
    lines = [str] + lines
    output = File.new("lib/nsxt_policy_client/nsxt_policy_client.rb", "w")
    lines.each { |line| output.write line }
    output.close
  end
end

task default: "swagger:nsxt_manager_client"
