#!/bin/bash

set -e

export BUNDLE_APP_CONFIG=$(mktemp -d $TMPDIR/bundler_config_XXXXXX)
export BUNDLE_CACHE_PATH="vendor/package"
export BUNDLE_WITHOUT="development:test"

bundle package

rm -rf $BUNDLE_APP_CONFIG
