#!/bin/bash
# When vendoring gems, vendor on a linux machine as that is the operating system that
set -e

if [ "$(uname -s)" == "Darwin" ]; then
    echo "Please run on a linux machine so that we vendor linux specific pre compiled libraries"
else
  export BUNDLE_APP_CONFIG=$(mktemp -d $TMPDIR/bundler_config_XXXXXX)
  export BUNDLE_CACHE_PATH="vendor/package"
  export BUNDLE_WITHOUT="development:test"

  bundle package

  rm -rf $BUNDLE_APP_CONFIG
fi