#!/bin/bash
# When vendoring gems, vendor on a linux machine as that is the operating system that
set -e

export BUNDLE_GEMFILE="src/vsphere_cpi/Gemfile"
export BUNDLE_APP_CONFIG=$(mktemp -d $TMPDIR/bundler_config_XXXXXX)
export BUNDLE_CACHE_PATH="vendor/package"
export BUNDLE_WITHOUT="development:test"

bundle package

rm -rf $BUNDLE_APP_CONFIG