#!/bin/bash

set -ex

cpi_dir=$(cd $(dirname $0)/../ && pwd)
gem_dir=$cpi_dir/src/vsphere_cpi

cleanup() {
  cd $gem_dir
  rm Gemfile*
}

trap cleanup EXIT

(
  cd $gem_dir
  cat > 'Gemfile' <<EOF
source "https://rubygems.org"

gem "bosh_vsphere_cpi"
EOF

  bundle package
)
