---
groups:
  - name: bosh-vsphere-cpi-release
    jobs:
      - create-jumpbox
      - build-candidate
      - bats-ubuntu-manual
      - bats-centos-manual
      - lifecycle
      - promote-candidate

  - name: ubuntu
    jobs:
      - build-candidate
      - bats-ubuntu-manual
      - promote-candidate

  - name: centos
    jobs:
      - build-candidate
      - bats-centos-manual
      - promote-candidate

jobs:
  - name: create-jumpbox
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-release}

      - task: sleep
        file: bosh-cpi-release/ci/tasks/create-jumpbox.yml

  - name: build-candidate
    serial: true
    plan:
      - aggregate:
          - {trigger: false, get: bosh-cpi-release}
          - {trigger: false, get: version-semver,   params: {bump: patch}}

      - put: version-semver
        params: {file: version-semver/number}

      - task: build
        file: bosh-cpi-release/ci/tasks/build-candidate.yml

      - put: bosh-cpi-dev-artifacts
        params: {from: build/out/.*\.tgz}

  - name: lifecycle
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts} # used for job chaining only not for tasks
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-release}
        - {trigger: false,                            get: stemcell, resource: vsphere-ubuntu-stemcell}

      - task: test
        file: bosh-cpi-release/ci/tasks/run-lifecycle.yml
        config:
          params:
            BOSH_VSPHERE_CPI_HOST:                         {{lifecycle_VSPHERE_HOST}}
            BOSH_VSPHERE_CPI_USER:                         {{lifecycle_VSPHERE_USER}}
            BOSH_VSPHERE_CPI_PASSWORD:                     {{lifecycle_VSPHERE_PASSWORD}}
            BOSH_VSPHERE_CPI_ADMIN_USER:                   {{lifecycle_VSPHERE_ADMIN_USER}}
            BOSH_VSPHERE_CPI_ADMIN_PASSWORD:               {{lifecycle_VSPHERE_ADMIN_PASSWORD}}
            BOSH_VSPHERE_VLAN:                             {{lifecycle_VSPHERE_VLAN}}
            BOSH_VSPHERE_CPI_DATACENTER:                   {{lifecycle_VSPHERE_DATACENTER}}
            BOSH_VSPHERE_CPI_CLUSTER:                      {{lifecycle_VSPHERE_CLUSTER}}
            BOSH_VSPHERE_CPI_DATASTORE_PATTERN:            {{lifecycle_VSPHERE_DATASTORE_PATTERN}}
            BOSH_VSPHERE_CPI_PERSISTENT_DATASTORE_PATTERN: {{lifecycle_VSPHERE_PERSISTENT_DATASTORE_PATTERN}}
            BOSH_VSPHERE_CPI_SECOND_DATASTORE:             {{lifecycle_VSPHERE_SECOND_DATASTORE}}
            BOSH_VSPHERE_CPI_LOCAL_DATASTORE_PATTERN:      {{lifecycle_VSPHERE_LOCAL_DATASTORE_PATTERN}}
            BOSH_VSPHERE_CPI_RESOURCE_POOL:                {{lifecycle_VSPHERE_RESOURCE_POOL}}
            BOSH_VSPHERE_CPI_SECOND_RESOURCE_POOL:         {{lifecycle_VSPHERE_SECOND_RESOURCE_POOL}}
            BOSH_VSPHERE_CPI_SECOND_CLUSTER:               {{lifecycle_VSPHERE_SECOND_CLUSTER}}
            BOSH_VSPHERE_CPI_SECOND_CLUSTER_DATASTORE:     {{lifecycle_VSPHERE_SECOND_CLUSTER_DATASTORE}}
            BOSH_VSPHERE_CPI_SECOND_CLUSTER_RESOURCE_POOL: {{lifecycle_VSPHERE_SECOND_CLUSTER_RESOURCE_POOL}}
            BOSH_VSPHERE_CPI_VM_FOLDER:                    {{lifecycle_VSPHERE_VM_FOLDER}}
            BOSH_VSPHERE_CPI_TEMPLATE_FOLDER:              {{lifecycle_VSPHERE_TEMPLATE_FOLDER}}
            BOSH_VSPHERE_CPI_DISK_PATH:                    {{lifecycle_VSPHERE_DISK_PATH}}

  - name: bats-ubuntu-manual
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts}
        - {trigger: false, passed: [build-candidate], get: version-semver}
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-release}
        - {trigger: false,                            get: bosh-init}
        - {trigger: false,                            get: bosh-release}
        - {trigger: false,                            get: stemcell, resource: vsphere-ubuntu-stemcell}
        - {trigger: false,                            get: bats}

      - put: vsphere-5.1-environment
        params:
          acquire: true

      - task: show_env
        file: bosh-cpi-release/ci/tasks/show_env.yml

      - task: setup-director
        file: bosh-cpi-release/ci/tasks/setup-director.yml
        config:
          params:
            base_os:                                ubuntu
            network_type_to_test:                   manual
            BOSH_VSPHERE_VCENTER:                   {{VCENTER_IP}}
            BOSH_VSPHERE_VCENTER_USER:              {{VCENTER_USER}}
            BOSH_VSPHERE_VCENTER_PASSWORD:          {{VCENTER_PASSWORD}}
            BOSH_VSPHERE_VCENTER_DC:                {{VCENTER_DC}}
            BOSH_VSPHERE_VCENTER_CLUSTER:           {{VCENTER_CLUSTER}}
            BOSH_VSPHERE_VCENTER_VM_FOLDER:         {{ubuntu_VCENTER_VM_FOLDER}}
            BOSH_VSPHERE_VCENTER_TEMPLATE_FOLDER:   {{ubuntu_VCENTER_TEMPLATE_FOLDER}}
            BOSH_VSPHERE_VCENTER_DATASTORE_PATTERN: {{VCENTER_DATASTORE_PATTERN}}
            BOSH_VSPHERE_VCENTER_DISK_PATH:         {{ubuntu_VCENTER_DISK_PATH}}
            BOSH_VSPHERE_VCENTER_VLAN:              {{VCENTER_VLAN}}

      - task: test
        file: bosh-cpi-release/ci/tasks/run-bats.yml
        config:
          params:
            base_os:                                      ubuntu
            network_type_to_test:                         manual
            BAT_STEMCELL_NAME:                            {{ubuntu_BAT_STEMCELL_NAME}}
            BAT_VLAN:                                     {{VCENTER_VLAN}}
            BAT_VCAP_PASSWORD:                            {{BAT_VCAP_PASSWORD}}
            BAT_SECOND_NETWORK_VLAN:                      {{ubuntu_BAT_SECOND_NETWORK_VLAN}}
            BOSH_VSPHERE_NTP_SERVER:                      {{VCENTER_NTP_SERVER}}
            BOSH_VSPHERE_NET_ID:                          {{VCENTER_VLAN}}
            BOSH_VSPHERE_VCENTER:                         {{VCENTER_IP}}
            BOSH_VSPHERE_VCENTER_USER:                    {{VCENTER_USER}}
            BOSH_VSPHERE_VCENTER_PASSWORD:                {{VCENTER_PASSWORD}}
            BOSH_VSPHERE_VCENTER_DC:                      {{VCENTER_DC}}
            BOSH_VSPHERE_VCENTER_CLUSTER:                 {{VCENTER_CLUSTER}}
            BOSH_VSPHERE_VCENTER_RESOURCE_POOL:           {{VCENTER_RESOURCE_POOL}}
            BOSH_VSPHERE_VCENTER_DATASTORE_PATTERN:       {{VCENTER_DATASTORE_PATTERN}}
            BOSH_VSPHERE_VCENTER_UBOSH_DATASTORE_PATTERN: {{VCENTER_DATASTORE_PATTERN}}
            BOSH_VSPHERE_VCENTER_FOLDER_PREFIX:           {{ubuntu_BOSH_VSPHERE_VCENTER_FOLDER_PREFIX}}

      - task: teardown-director
        file: bosh-cpi-release/ci/tasks/teardown-director.yml

      - put: vsphere-5.1-environment
        params:
          release: vsphere-5.1-environment

  - name: bats-centos-manual
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts}
        - {trigger: false, passed: [build-candidate], get: version-semver}
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-release}
        - {trigger: false,                            get: bosh-init}
        - {trigger: false,                            get: bosh-release}
        - {trigger: false,                            get: stemcell, resource: vsphere-centos-stemcell}
        - {trigger: false,                            get: bats}

      - put: vsphere-5.1-environment
        params:
          acquire: true

      - task: show_env
        file: bosh-cpi-release/ci/tasks/show_env.yml

      - task: setup-director
        file: bosh-cpi-release/ci/tasks/setup-director.yml
        config:
          params:
            base_os:                                centos
            network_type_to_test:                   manual
            BOSH_VSPHERE_VCENTER:                   {{VCENTER_IP}}
            BOSH_VSPHERE_VCENTER_USER:              {{VCENTER_USER}}
            BOSH_VSPHERE_VCENTER_PASSWORD:          {{VCENTER_PASSWORD}}
            BOSH_VSPHERE_VCENTER_DC:                {{VCENTER_DC}}
            BOSH_VSPHERE_VCENTER_CLUSTER:           {{VCENTER_CLUSTER}}
            BOSH_VSPHERE_VCENTER_VM_FOLDER:         {{centos_VCENTER_VM_FOLDER}}
            BOSH_VSPHERE_VCENTER_TEMPLATE_FOLDER:   {{centos_VCENTER_TEMPLATE_FOLDER}}
            BOSH_VSPHERE_VCENTER_DATASTORE_PATTERN: {{VCENTER_DATASTORE_PATTERN}}
            BOSH_VSPHERE_VCENTER_DISK_PATH:         {{centos_VCENTER_DISK_PATH}}
            BOSH_VSPHERE_VCENTER_VLAN:              {{VCENTER_VLAN}}

      - task: test
        file: bosh-cpi-release/ci/tasks/run-bats.yml
        config:
          params:
            base_os:                                      centos
            network_type_to_test:                         manual
            BAT_STEMCELL_NAME:                            {{centos_BAT_STEMCELL_NAME}}
            BAT_VLAN:                                     {{VCENTER_VLAN}}
            BAT_VCAP_PASSWORD:                            {{BAT_VCAP_PASSWORD}}
            BAT_SECOND_NETWORK_VLAN:                      {{centos_BAT_SECOND_NETWORK_VLAN}}
            BOSH_VSPHERE_NTP_SERVER:                      {{VCENTER_NTP_SERVER}}
            BOSH_VSPHERE_NET_ID:                          {{VCENTER_VLAN}}
            BOSH_VSPHERE_VCENTER:                         {{VCENTER_IP}}
            BOSH_VSPHERE_VCENTER_USER:                    {{VCENTER_USER}}
            BOSH_VSPHERE_VCENTER_PASSWORD:                {{VCENTER_PASSWORD}}
            BOSH_VSPHERE_VCENTER_DC:                      {{VCENTER_DC}}
            BOSH_VSPHERE_VCENTER_CLUSTER:                 {{VCENTER_CLUSTER}}
            BOSH_VSPHERE_VCENTER_RESOURCE_POOL:           {{VCENTER_RESOURCE_POOL}}
            BOSH_VSPHERE_VCENTER_DATASTORE_PATTERN:       {{VCENTER_DATASTORE_PATTERN}}
            BOSH_VSPHERE_VCENTER_UBOSH_DATASTORE_PATTERN: {{VCENTER_DATASTORE_PATTERN}}
            BOSH_VSPHERE_VCENTER_FOLDER_PREFIX:           {{centos_BOSH_VSPHERE_VCENTER_FOLDER_PREFIX}}

      - task: teardown-director
        file: bosh-cpi-release/ci/tasks/teardown-director.yml

      - put: vsphere-5.1-environment
        params:
          release: vsphere-5.1-environment

  - name: promote-candidate
    serial: true
    plan:
    - aggregate:
      - {trigger: false,  passed: [lifecycle, bats-ubuntu-manual, bats-centos-manual], get: bosh-cpi-dev-artifacts}
      - {trigger: false, passed: [lifecycle, bats-ubuntu-manual, bats-centos-manual], get: bosh-cpi-release}
      - {trigger: false, get: release-version-semver, params: {bump: major}}

    - task: promote
      file: bosh-cpi-release/ci/tasks/promote-candidate.yml
      config:
        params:
          aws_access_key_id:     {{s3_vsphere_cpi_blobwriter_access_key}}
          aws_secret_access_key: {{s3_vsphere_cpi_blobwriter_secret_key}}

    - put: bosh-cpi-release
      params: {repository: promote/bosh-cpi-release, rebase: true, tag_prefix: "v", tag: promote/integer_version}

    - put: release-version-semver
      params: {file: release-version-semver/number}

resources:
  - name: bosh-cpi-dev-artifacts
    type: s3
    source:
      regexp:            bosh-vsphere-cpi\.tgz
      bucket:            {{s3_vsphere_cpi_bucket}}
      region_name:       us-east-1
      access_key_id:     {{s3_vsphere_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vsphere_cpi_blobwriter_secret_key}}

  - name: bosh-cpi-release
    type: git
    source:
      uri:         git@github.com:cloudfoundry-incubator/bosh-vsphere-cpi-release.git
      branch:      master
      private_key: {{github_deployment_key__bosh-vsphere-cpi-release}}

  - name: version-semver
    type: semver
    source:
      key:               current-version
      bucket:            {{s3_vsphere_cpi_bucket}}
      access_key_id:     {{s3_vsphere_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vsphere_cpi_blobwriter_secret_key}}

  - name: release-version-semver
    type: semver
    source:
      key:               release-current-version
      bucket:            {{s3_vsphere_cpi_bucket}}
      access_key_id:     {{s3_vsphere_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vsphere_cpi_blobwriter_secret_key}}

  - name: bosh-init
    type: s3
    source:
      regexp:      bosh-init-([0-9.]+)-linux-amd64
      bucket:      {{s3_bosh_init_bucket}}
      region_name: us-east-1

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: vsphere-ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

  - name: vsphere-centos-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-centos-7-go_agent

  - name: bats
    type: git
    source:
      uri:    https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master

  - name: vsphere-5.1-environment
    type: pool
    source:
      pool: vsphere-5.1
      uri: git@github.com:cloudfoundry/bosh-cpi-environments.git
      branch: master
      private_key: {{github_deployment_key__bosh-cpi-environments}}
