require 'open3'
require 'time'
require 'shellwords'

# Remove did_you_mean as it's very annoying in a Rakefile
DidYouMean::Correctable.send(:remove_method, :to_s) if defined? DidYouMean

# Colorize error messages when the trace output is a TTY
module ColorizeExceptionMessageDetails
  def display_exception_message_details(ex)
    return super unless (options.trace_output || $stderr)&.isatty
    if ex.instance_of?(RuntimeError)
      trace "\e[31;01m#{ex.message}\e[0m"
    else
      trace "\e[31;01m#{ex.class.name}: \e[0m#{ex.message}"
    end
  end
end
Rake::Application.send(:prepend, ColorizeExceptionMessageDetails)

# A Concourse target as recognized by `fly`. For more information see the
# {https://concourse.ci/fly-cli.html documentation} on the `fly` CLI.
class Target
  # @return [[Target]] a list of the targets currently known to `fly`
  def self.list
    @list ||= IO.popen(%w[fly targets]).map { |t| new(*t.split(nil, 4)) }
  end

  attr_reader :name, :url, :team

  # @return [Time] the expiry time of the target's authentication token
  attr_reader :expiry

  def initialize(name, url, team, expiry)
    @name, @url, @team, @expiry = name, url, team, Time.rfc2822(expiry)
  end
end

DOCKER_NAME = ENV.fetch('DOCKER_NAME', 'vcpici/vcpi-main')

namespace :docker do
  desc 'Build a docker image from the Dockerfile'
  task(:make) { sh 'docker', 'build', '-t', DOCKER_NAME, 'docker' }

  desc "Push the docker image to '#{DOCKER_NAME}'"
  task(:push) { sh 'docker', 'push', DOCKER_NAME }

  desc "Pull the docker image from '#{DOCKER_NAME}'"
  task(:pull) { sh 'docker', 'pull', DOCKER_NAME }
end

desc "Pull, build, and push the docker image '#{DOCKER_NAME}'"
task docker: %w[docker:pull docker:make docker:push]

desc 'Create or update the pipeline configuration'
task :pipeline, [:name] => 'pipeline.yml' do |t, args|
  # Default to the unexpired target expiring furthest in the future known to
  # `fly`
  CONCOURSE = ENV.fetch('CONCOURSE') do
    authorized = Target.list.select { |t| t.expiry > Time.now }
    unless target = authorized.max_by(&:expiry)
      fail 'No Concourse target specified and all targets are expired'
    end
    target.name
  end

  # Ensure that the remote host is set from DBCHOST
  DBCHOST = ENV.fetch('DBCHOST') do
    fail 'DBCHOST must be set to the unqualified hostname of your DBC host'
  end
  dbcfqdn = "#{DBCHOST}.eng.vmware.com"

  # Get the remote user name from DBCUSER, the SSH configuration for DBCHOST, or
  # the current user name
  DBCUSER = ENV.fetch('DBCUSER') do
    output, _, status = Open3.capture3('ssh', '-G', dbcfqdn)
    break nil unless status.success?
    record = output.each_line(chomp: true).map do |text|
      text.split(nil, 2)
    end.find { |option, _| option == 'user' }
    break record[1] unless record.nil?
  end || (require 'etc'; Etc.getpwuid.name)

  # Find the SSH identity file to use from the SSH configuration for DBCHOST
  output, _, status = Open3.capture3('ssh', '-G', dbcfqdn)
  fail "Unable to get SSH configuration for #{DBCHOST}" unless status.success?
  dbc_ssh_key = output.each_line(chomp: true).map do |text|
    text.split(nil, 2)
  end.find do |option, v|
    option == 'identityfile' && File.exist?(File.expand_path(v))
  end or fail "No SSH identity file available for #{DBCHOST}"
  dbc_ssh_key = File.expand_path(dbc_ssh_key[1])

  # Get the git branch name
  branch = ENV.fetch('BRANCH') { `git symbolic-ref -q --short HEAD`.strip }

  # Set the pipeline name to be vSphere-CPI when on the master branch or
  # vSphere-CPI-#{branch} when on another branch. If the branch name is
  # indeterminate (because HEAD is detached) then the pipeline name must be
  # provided as the name argument to this task.
  args.with_defaults(name: ENV.fetch('PIPELINE') do
    if branch.empty?
      fail 'Pipeline name must be specified if HEAD is detached'
    end
    branch == 'master' ? 'vSphere-CPI' : "vcpi-#{branch}"
  end)

  # Default to master if the branch name is indeterminate (because HEAD is
  # detached).
  branch = !branch.empty? ? branch : 'master'

  sh '/bin/bash', '-ec', [
    "fly -t #{CONCOURSE.shellescape} set-pipeline",
    "-p #{args.name.shellescape}",
    "-c #{t.prerequisites.first.shellescape}",
    "-v vcpi_branch=#{branch.shellescape}",
    "-v dbc_host=#{DBCHOST.shellescape}",
    "-v dbc_user=#{DBCUSER.shellescape}",
    "-v dbc_key=\"$(cat #{dbc_ssh_key.shellescape})\"",
    '-v s3_vsphere_cpi_bucket=bosh-vsphere-cpi-release',
    '-l <(secret show ~/.dot/vcpi-ci.gpg)'
  ].join(' ')
end

task default: :pipeline
