require 'shellwords'

DidYouMean::Correctable.send(:remove_method, :to_s) if defined? DidYouMean

module ColorizeExceptionMessageDetails
  def display_exception_message_details(ex)
    return super unless (options.trace_output || $stderr)&.isatty
    if ex.instance_of?(RuntimeError)
      trace "\e[31;01m#{ex.message}\e[0m"
    else
      trace "\e[31;01m#{ex.class.name}: \e[0m#{ex.message}"
    end
  end
end
Rake::Application.send(:prepend, ColorizeExceptionMessageDetails)

DOCKER_NAME = ENV.fetch('DOCKER_NAME', 'vcpici/vcpi-main')

namespace :docker do
  desc 'Build a docker image from the Dockerfile'
  task :make do |t|
    sh 'docker', 'build', '-t', DOCKER_NAME, 'docker'
  end

  desc "Push the docker image to '#{DOCKER_NAME}'"
  task :push do |t|
    sh 'docker', 'push', DOCKER_NAME
  end

  desc "Pull the docker image from '#{DOCKER_NAME}'"
  task :pull do |t|
    sh 'docker', 'pull', DOCKER_NAME
  end
end

desc "Pull, build, and push the docker image '#{DOCKER_NAME}'"
task docker: ['docker:pull', 'docker:make', 'docker:push']

desc 'Create or update the pipeline configuration'
task :pipeline, :name do |t, args|
  TARGET = ENV.fetch('CONCOURSE_TARGET', 'main')

  DBCHOST = ENV.fetch('DBCHOST') do
    fail 'DBCHOST must be set to the unqualified hostname of your DBC host'
  end
  DBCUSER = ENV.fetch('DBCUSER') { require 'etc'; Etc.getpwuid.name }

  branch = ENV.fetch('BRANCH') { `git symbolic-ref -q --short HEAD` }
  branch.strip!

  args.with_defaults(name: ENV.fetch('PIPELINE') do
    if branch.empty?
      fail 'Pipeline name must be specified if HEAD is detached'
    end
    %w[master vmware-ci].include?(branch) ? 'vsphere-cpi' : "vcpi-#{branch}"
  end)

  branch = !branch.empty? ? branch : 'master'

  sh '/bin/bash', '-c', [
    "fly -t #{TARGET.shellescape}",
    "set-pipeline -p #{args.name.shellescape} -c pipeline.yml",
    "-v vcpi_branch=#{branch.shellescape}",
    "-v dbc_host=#{DBCHOST.shellescape}",
    "-v dbc_user=#{DBCUSER.shellescape}",
    '-v dbc_key="$(cat ~/.ssh/id_rsa)"',
    '-v s3_vsphere_cpi_bucket=vcpi-ci-test',
    '-l <(secret show ~/.dot/vcpi-ci.gpg)'
  ].join(' ')
end

task default: :pipeline
